"""added username

Revision ID: 38613c4f16d5
Revises: 80c24cc4bd89
Create Date: 2021-08-12 09:10:51.674225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38613c4f16d5'
down_revision = '80c24cc4bd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
