"""remove author

Revision ID: e47c843a6860
Revises: f26432df1173
Create Date: 2021-09-23 10:49:17.193074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47c843a6860'
down_revision = 'f26432df1173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
